---
- name: grab linux facts
  hosts: web
  gather_facts: true

- name: build developer report
  hosts: node1
  gather_facts: false
  
  vars:
    file_path: /var/www/html/report

  tasks:

    - name: install web package
      become: true
      yum:
        name: httpd
        state: present

    - name: use developer report
      include_role:
        name: "../../roles/developer_report"
        
  handlers:
    - name: restart httpd service 
      become: true
      service:
        name: httpd
        state: restarted


